unit uphosphoricons;

{ The toolbar's icons, as PNG bytes.

  GENERATED BY tools/gen-icons.py. NEVER HAND-EDIT THIS FILE. The drawing is in
  the script, which is where a change to an icon belongs; an edit here is lost
  the next time anybody regenerates, and `python tools/gen-icons.py --check` is
  what notices.

  WHY BYTES IN A UNIT rather than images in the .lfm. A TImageList streams its
  pictures into the form file as one binary blob, and src/umainform.lfm is a file
  people edit by hand: a blob there cannot be reviewed, cannot be diffed and
  cannot be changed without a designer. These are decoded into an empty list at
  FormCreate instead, which costs nine PNG decodes of a few hundred bytes each.

  TWO RESOLUTIONS, AND THAT IS THE WHOLE POINT. A single-resolution image list is
  scaled by the widgetset; the two widgetsets scale differently, one giving a
  blurred mark and the other a missing one, and neither is a build failure -- so
  nobody finds out until a screenshot arrives from the other platform.
  Application.Scaled is True (phosphoride.lpr), so a 150% Windows machine asks
  for the 24 the first time it draws.

  MIT License. Copyright (c) 2026 Andre Murta.
}

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Graphics, ImgList;

const
  { The .lfm carries these numbers as ImageIndex. They are named here so that a
    reordering is one edit in the generator and not nine silent ones. }
  iconNew = 0;
  iconOpen = 1;
  iconSave = 2;
  iconRun = 3;
  iconStop = 4;
  iconCheckSyntax = 5;
  iconToggleBreakpoint = 6;
  iconStepOver = 7;
  iconStepInto = 8;

  { ...and the gutter's, which is a SECOND list: SynEdit
    takes one image list for its marks and the toolbar takes
    another, and an index means nothing without knowing which. }
  markBreakArmed = 0;
  markBreakInert = 1;
  ToolbarIconCount = 9;
  GutterMarkCount = 2;

{ Fill AList with the nine icons, at both resolutions, replacing whatever was
  there. The list's own Width and Height are set to 16: the 24 is a REGISTERED
  RESOLUTION of the same list, not a second list, which is what lets the
  widgetset pick per monitor. }
procedure InstallToolbarIcons(AList: TCustomImageList);

{ The same, for the gutter's marks. SynEdit draws a TSynEditMark from the image
  list in BookMarkOptions.BookmarkImages, so this is a SECOND list rather than
  more slots in the first: mixing them would make the toolbar's indices and the
  gutter's share a numbering that nothing enforces. }
procedure InstallGutterMarks(AList: TCustomImageList);

implementation

const
  PngBreakArmed16: array[0..102] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $2E, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $BE, $60, $99, $B4, $F4, $7F, $64, $4C, $91, $66, $92, $0C, $C1, $A5,
    $99, $28, $43, $08, $69, $26, $68, $C8, $30, $30, $80, $E2, $40, $A4, $4A,
    $34, $52, $25, $21, $0D, $2D, $00, $00, $5D, $50, $8D, $05, $A0, $EE, $E2,
    $7A, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngBreakArmed24: array[0..113] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $39, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $00, $04, $96, $49, $4B, $FF, $C7, $86, $69, $66, $30, $55,
    $2C, $22, $D6, $70, $B2, $2D, $A1, $A9, $05, $A4, $1A, $4E, $B2, $25, $A3,
    $16, $8C, $00, $0B, $86, $7E, $3E, $A0, $4B, $51, $41, $97, $C2, $6E, $14,
    $0C, $0F, $00, $00, $9E, $2B, $30, $5C, $92, $13, $CF, $DD, $00, $00, $00,
    $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngBreakInert16: array[0..102] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $2E, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $BE, $60, $99, $B4, $F4, $7F, $64, $4C, $91, $66, $92, $0C, $C1, $A5,
    $99, $28, $43, $F0, $29, $24, $CA, $90, $61, $60, $00, $C5, $81, $48, $95,
    $68, $A4, $4A, $42, $1A, $5A, $00, $00, $14, $A4, $6F, $55, $70, $3D, $33,
    $9A, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngBreakInert24: array[0..118] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $3E, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $00, $04, $96, $49, $4B, $FF, $C7, $86, $69, $66, $30, $55,
    $2C, $22, $D6, $70, $B2, $2D, $A1, $A9, $05, $C4, $18, $40, $91, $25, $C4,
    $6A, $1C, $B5, $80, $7E, $16, $50, $3D, $92, $87, $7E, $3E, $A0, $4B, $51,
    $41, $97, $C2, $6E, $14, $0C, $0F, $00, $00, $A6, $89, $F4, $ED, $7E, $14,
    $49, $3C, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngCheckSyntax16: array[0..112] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $38, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $24, $01, $FB, $95, $5E, $FF, $41, $98, $62, $03, $F0, $1A, $82,
    $4B, $92, $68, $CD, $D8, $14, $11, $A5, $19, $9F, $3F, $49, $F2, $3B, $BA,
    $6D, $64, $05, $1C, $B2, $21, $64, $87, $3C, $45, $9A, $A9, $12, $E7, $43,
    $07, $00, $00, $D7, $41, $4A, $83, $D4, $73, $66, $59, $00, $00, $00, $00,
    $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngCheckSyntax24: array[0..134] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $4E, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $80, $18, $60, $BF, $D2, $EB, $3F, $4D, $0D, $87, $61, $9A,
    $5B, $40, $75, $4B, $D0, $0D, $27, $C9, $02, $42, $1A, $C8, $36, $9C, $18,
    $8D, $14, $B9, $9C, $98, $70, $A5, $A9, $05, $14, $1B, $8E, $2F, $F9, $51,
    $CD, $70, $5C, $86, $51, $3D, $49, $D2, $D4, $70, $9A, $04, $0B, $DD, $73,
    $2A, $DD, $CB, $9B, $D1, $7A, $63, $68, $02, $00, $60, $E5, $BC, $77, $7D,
    $52, $85, $4C, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngNew16: array[0..97] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $29, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $74, $20, $21, $AD, $E0, $3F, $3E, $4C, $94, $01, $9F, $3E, $BD, $C3,
    $8A, $87, $98, $01, $E8, $7E, $1F, $F5, $C2, $90, $8B, $46, $8A, $92, $32,
    $DD, $01, $00, $56, $50, $27, $A0, $2D, $3D, $DF, $DA, $00, $00, $00, $00,
    $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngNew24: array[0..111] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $37, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $E4, $82, $84, $B4, $82, $FF, $A4, $60, $B2, $2C, $F8, $F4, $E9,
    $1D, $41, $4C, $73, $0B, $60, $96, $8C, $5A, $40, $5B, $0B, $70, $A5, $9C,
    $D1, $20, $1A, $8D, $E4, $D1, $38, $18, $B5, $80, $D6, $15, $CE, $28, $80,
    $01, $00, $4A, $E9, $C9, $6B, $30, $9F, $31, $AA, $00, $00, $00, $00, $49,
    $45, $4E, $44, $AE, $42, $60, $82
  );
  PngOpen16: array[0..91] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $23, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $70, $B0, $A3, $46, $E2, $3F, $3A, $A6, $AF, $01, $0F, $16, $18,
    $FC, $27, $05, $8F, $1A, $30, $28, $0D, $18, $BA, $00, $00, $73, $10, $F8,
    $5B, $A7, $37, $69, $38, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42,
    $60, $82
  );
  PngOpen24: array[0..100] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $2C, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $80, $AA, $60, $47, $8D, $C4, $7F, $5C, $78, $D4, $02, $30,
    $78, $B0, $C0, $E0, $3F, $35, $F0, $A8, $05, $A3, $16, $8C, $5A, $30, $AC,
    $2D, $18, $05, $03, $02, $00, $65, $69, $43, $A0, $7F, $45, $92, $59, $00,
    $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngRun16: array[0..103] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $2F, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $58, $81, $FD, $4A, $AF, $FF, $20, $4C, $B1, $01, $64, $1B, $82,
    $6C, $00, $59, $06, $61, $33, $80, $24, $43, $70, $19, $40, $B4, $41, $34,
    $71, $C1, $C0, $C4, $C2, $08, $49, $F6, $00, $4F, $69, $57, $A9, $22, $12,
    $69, $7C, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngRun24: array[0..126] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $46, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $C0, $7E, $A5, $D7, $7F, $10, $A6, $B9, $05, $34, $B3, $04,
    $D9, $02, $9A, $58, $82, $6E, $01, $D5, $2D, $C2, $65, $01, $D5, $2C, $22,
    $64, $01, $C5, $96, $10, $63, $01, $45, $96, $10, $6B, $01, $D9, $16, $0D,
    $0A, $1F, $0C, $CD, $54, $34, $34, $73, $F2, $D0, $2C, $4D, $47, $01, $CD,
    $01, $00, $A7, $6C, $D2, $61, $C7, $B2, $DF, $EF, $00, $00, $00, $00, $49,
    $45, $4E, $44, $AE, $42, $60, $82
  );
  PngSave16: array[0..120] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $40, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $34, $C0, $BC, $EE, $C4, $7F, $18, $FE, $F4, $E9, $1D, $56, $8C, $AC,
    $86, $68, $03, $54, $A2, $26, $81, $F1, $C0, $19, $40, $96, $17, $88, $C1,
    $83, $D8, $00, $5C, $FE, $47, $0F, $07, $BC, $06, $24, $A4, $15, $60, $C5,
    $44, $1B, $40, $B1, $0B, $06, $C6, $80, $01, $03, $00, $E7, $8F, $AA, $60,
    $1C, $56, $30, $AE, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60,
    $82
  );
  PngSave24: array[0..131] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $4B, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A4, $00, $F3, $BA, $13, $FF, $D1, $F1, $A7, $4F, $EF, $F0, $62,
    $6C, $7A, $28, $B2, $40, $25, $6A, $12, $1C, $8F, $5A, $30, $30, $16, $50,
    $3D, $92, $C9, $C1, $A3, $16, $0C, $11, $0B, $08, $A5, $1E, $7C, $A9, $89,
    $24, $0B, $12, $D2, $0A, $F0, $62, $8A, $2D, $A0, $B9, $0F, $46, $2D, $A0,
    $AF, $05, $A3, $00, $1B, $00, $00, $A4, $3E, $B2, $FA, $A7, $E0, $D0, $FC,
    $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngStepInto16: array[0..103] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $2F, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $D4, $C0, $BC, $EE, $C4, $7F, $10, $1E, $35, $80, $0C, $03, $60, $1A,
    $D1, $31, $45, $86, $0C, $4C, $18, $0C, $2C, $48, $48, $2B, $F8, $8F, $8C,
    $E9, $6F, $00, $B2, $21, $34, $F5, $2A, $00, $DD, $B8, $4C, $BB, $94, $C4,
    $3C, $2E, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngStepInto24: array[0..123] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $43, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $43, $06, $98, $D7, $9D, $F8, $8F, $8C, $47, $2D, $18, $B5, $80,
    $7C, $83, $69, $62, $11, $4D, $0D, $A7, $8B, $05, $74, $89, $64, $64, $4B,
    $68, $5E, $5C, $0C, $DD, $02, $2F, $21, $AD, $E0, $3F, $08, $D3, $D4, $70,
    $9A, $58, $82, $6E, $38, $5D, $2C, $19, $5A, $41, $34, $A8, $01, $00, $80,
    $06, $AD, $55, $57, $20, $11, $8E, $00, $00, $00, $00, $49, $45, $4E, $44,
    $AE, $42, $60, $82
  );
  PngStepOver16: array[0..104] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $30, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $D4, $05, $E6, $75, $27, $FE, $13, $C2, $14, $1B, $40, $94, $41,
    $F8, $0C, $1F, $62, $81, $9A, $90, $56, $F0, $1F, $84, $29, $D2, $4C, $B6,
    $21, $03, $6F, $00, $C5, $61, $40, $2C, $00, $00, $3E, $53, $59, $F9, $AD,
    $B8, $29, $86, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngStepOver24: array[0..126] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $46, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $60, $C0, $80, $79, $DD, $89, $FF, $20, $4C, $73, $0B, $48,
    $B6, $08, $5D, $23, $29, $98, $E6, $16, $50, $35, $D8, $68, $66, $30, $C5,
    $71, $30, $68, $52, $D1, $D0, $04, $09, $69, $05, $FF, $41, $98, $A6, $86,
    $D3, $C4, $12, $74, $C3, $A9, $6E, $C9, $A8, $05, $03, $1F, $C9, $83, $1A,
    $00, $00, $7B, $74, $C4, $C7, $FF, $34, $64, $9E, $00, $00, $00, $00, $49,
    $45, $4E, $44, $AE, $42, $60, $82
  );
  PngStop16: array[0..82] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $1A, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $18, $E0, $82, $B5, $FE, $7F, $7C, $78, $D4, $80, $91, $61, $C0,
    $08, $04, $00, $F6, $D0, $8E, $41, $04, $17, $CE, $06, $00, $00, $00, $00,
    $49, $45, $4E, $44, $AE, $42, $60, $82
  );
  PngStop24: array[0..94] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $26, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $80, $66, $E0, $82, $B5, $FE, $7F, $52, $F0, $A8, $05, $A3,
    $16, $8C, $5A, $30, $6A, $01, $2D, $2C, $18, $05, $A3, $80, $68, $00, $00,
    $82, $D1, $40, $20, $93, $42, $88, $1A, $00, $00, $00, $00, $49, $45, $4E,
    $44, $AE, $42, $60, $82
  );
  PngToggleBreakpoint16: array[0..90] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $10, $00, $00, $00, $10, $08, $06, $00, $00, $00, $1F,
    $F3, $FF, $61, $00, $00, $00, $22, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $58, $C1, $32, $69, $E9, $FF, $D8, $30, $45, $9A, $89, $36, $64,
    $D4, $00, $2A, $18, $40, $71, $34, $8E, $40, $00, $00, $14, $A4, $6F, $55,
    $0A, $14, $97, $E1, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60,
    $82
  );
  PngToggleBreakpoint24: array[0..118] of Byte = (
    $89, $50, $4E, $47, $0D, $0A, $1A, $0A, $00, $00, $00, $0D, $49, $48, $44,
    $52, $00, $00, $00, $18, $00, $00, $00, $18, $08, $06, $00, $00, $00, $E0,
    $77, $3D, $F8, $00, $00, $00, $3E, $49, $44, $41, $54, $78, $DA, $63, $60,
    $18, $05, $A3, $00, $06, $96, $49, $4B, $FF, $47, $C6, $34, $33, $98, $AA,
    $16, $11, $32, $9C, $22, $4B, $88, $35, $9C, $6C, $4B, $68, $6A, $01, $A9,
    $86, $93, $6C, $C9, $A8, $05, $23, $20, $15, $D1, $25, $A3, $D1, $A5, $A8,
    $A0, $4B, $61, $37, $0A, $86, $3E, $00, $00, $A2, $5A, $12, $AC, $86, $6F,
    $4B, $24, $00, $00, $00, $00, $49, $45, $4E, $44, $AE, $42, $60, $82
  );
{ One icon, two sizes. AddMultipleResolutions wants them smallest first -- its
  own comment in imglist.pp says so -- and it is the only call here that would
  still "work" with one image and quietly give back the blur this unit exists to
  avoid. }
procedure AddPair(AList: TCustomImageList; const A16, A24: array of Byte);
var
  img16, img24: TPortableNetworkGraphic;
  { TYPED, AND THAT IS NOT DECORATION. AddMultipleResolutions is overloaded on
    `array of TCustomBitmap` and `array of TRasterImage`, and a PNG is both --
    TPortableNetworkGraphic descends from TFPImageBitmap, which descends from
    TCustomBitmap, which descends from TRasterImage -- so passing a bare open
    array is "Can't determine which overloaded function to call". Naming the
    array type picks one. }
  pair: array[0..1] of TCustomBitmap;
  mem: TMemoryStream;
begin
  img16 := TPortableNetworkGraphic.Create;
  img24 := TPortableNetworkGraphic.Create;
  mem := TMemoryStream.Create;
  try
    mem.Write(A16[0], Length(A16));
    mem.Position := 0;
    img16.LoadFromStream(mem);
    mem.Clear;
    mem.Write(A24[0], Length(A24));
    mem.Position := 0;
    img24.LoadFromStream(mem);
    pair[0] := img16;
    pair[1] := img24;
    AList.AddMultipleResolutions(pair);
  finally
    mem.Free;
    img24.Free;
    img16.Free;
  end;
end;

procedure Prepare(AList: TCustomImageList);
begin
  AList.Clear;
  AList.Width := 16;
  AList.Height := 16;
  { BEFORE the first Add, because registering a resolution afterwards leaves the
    images already in the list without one. }
  AList.RegisterResolutions([16, 24]);
end;

procedure InstallToolbarIcons(AList: TCustomImageList);
begin
  Prepare(AList);
  AddPair(AList, PngNew16, PngNew24);
  AddPair(AList, PngOpen16, PngOpen24);
  AddPair(AList, PngSave16, PngSave24);
  AddPair(AList, PngRun16, PngRun24);
  AddPair(AList, PngStop16, PngStop24);
  AddPair(AList, PngCheckSyntax16, PngCheckSyntax24);
  AddPair(AList, PngToggleBreakpoint16, PngToggleBreakpoint24);
  AddPair(AList, PngStepOver16, PngStepOver24);
  AddPair(AList, PngStepInto16, PngStepInto24);
end;

procedure InstallGutterMarks(AList: TCustomImageList);
begin
  Prepare(AList);
  AddPair(AList, PngBreakArmed16, PngBreakArmed24);
  AddPair(AList, PngBreakInert16, PngBreakInert24);
end;

end.
